version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/web"
    schedule:
      interval: "weekly"
    labels:
      - dependencies
    commit-message:
      prefix: "[Dependency] "
    groups:
      all-updates:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/src/api"
    schedule:
      interval: "weekly"
    labels:
      - dependencies
    commit-message:
      prefix: "[Dependency] "
    groups:
      all-updates:
        patterns:
          - "*"