version: '3.9'

services:

  lineupx_db:
    container_name: lineupx_db
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=LineupX
    volumes:
      - lineupx_db:/data/db
      - ./src/api/__test__/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

  lineupx_api:
    container_name: lineupx_api
    image: api
    ports:
      - 1337:1337
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./src/api
      dockerfile: Dockerfile
    volumes:
      - ./src/api:/home/app
    depends_on:
      - lineupx_db

volumes:
  lineupx_db: