version: '3.9'

services:

  lineupx_db:
    container_name: lineupx_db
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - lineupx_db:/data/db

  lineupx_api:
    container_name: lineupx_api
    image: api
    ports:
      - 1337:1337
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./src/api
      dockerfile: Dockerfile
    volumes:
      - ./src/api:/home/app

volumes:
  lineupx_db: