services:

  lineupx_db:
    container_name: lineupx_db
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=LineupX
    volumes:
      - lineupx_db:/data/db
      - ./src/api/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - ./src/api/scripts/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./src/api/data:/docker-entrypoint-initdb.d/data
    command: ["sh", "-c", "mongod > /dev/null 2>&1"]

  lineupx_api:
    container_name: lineupx_api
    image: api
    ports:
      - 1337:1337
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./src/api
      dockerfile: Dockerfile
    volumes:
      - ./src/api:/home/app
      - /home/app/node_modules
    depends_on:
      - lineupx_db
  
  lineupx_web:
    container_name: lineupx_web
    image: web
    ports:
      - 5173:5173
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./src/web
      dockerfile: Dockerfile
    volumes:
      - ./src/web:/home/web
      - /home/web/node_modules
    depends_on:
      - lineupx_api
volumes:
  lineupx_db: