name: Deployment to Web - Preview

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches-ignore:
      - main

jobs:
  preview-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Change Directory
        run: cd src/web

      - name: Install Vercel CLI
        run: npm install -g vercel
      
      - name: Pull Vercel Env
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }} 
      
      - name: Build Project
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Deploy Project
        run: vercel --prebuilt --token=${{ secrets.VERCEL_TOKEN }}