name: Compile Node.js

on: [pull_request, push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: cd api
      - run: npm ci
      - run: npm run build
