name: Compile Node.js

on: [pull_request, push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
        working-directory: api
      - name: Build
        run: timeout 3s npm run build
        working-directory: api
