name: Prettier

on:
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Install dependencies
        run: npm install

      - name: Check for unformatted files
        id: prettier_check
        run: |
          npx prettier --check "src/**/*.{js,jsx,ts,tsx,json,css,md}" || echo "Prettier found unformatted files"

      - name: Prettify Code
        run: |
          npx prettier --write "src/**/*.{js,jsx,ts,tsx,json,css,md}"

      - name: Commit changes
        run: |
          git config --local user.email "${{ github.event.pusher.email }}"
          git config --local user.name "${{ github.event.pusher.name }}"
          git add .
          FILES=$(git diff --name-only --staged)
          if [ -z "$FILES" ]; then
            echo "No changes to commit."
            exit 0
          else
            git commit -m "Prettify Code: $FILES"
          fi

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.REPO_SCOPED_TOKEN }}
          branch: ${{ github.head_ref }}

      - name: Fail if Prettier found unformatted files
        if: steps.prettier_check.outcome == 'failure'
        run: exit 1