uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Prettify Code
        run: |
          npm install
          npx prettier --write "src/**/*.{js,jsx,ts,tsx,json,css,md}"
      
      - name: Commit changes
        if: success()
        run: |
          git config --local user.email "${{ github.event.pusher.email }}"
          git config --local user.name "${{ github.event.pusher.name }}"
          git add .
          FILES=$(git diff --name-only --staged)
          if [ -z "$FILES" ]; then
            echo "No changes to commit."
            exit 0
          else
            git commit -m "Prettify Code: $FILES"
          fi
      
      - name: Push changes
        if: success()
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.REPO_SCOPED_TOKEN }}
          branch: ${{ github.head_ref }}