name: Prettier

on:
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Check Code Formatting
        run: |
          npm install
          npx prettier --check "src/**/*.{js,jsx,ts,tsx,json,css,md}"